package console

// cmdMeta describes one syscon command for cmdinfo output and completion.
type cmdMeta struct {
	description string
	params      string
	subs        string
}

var (
	scErrors = map[string]string{
		"1":    "System error",
		"1001": "BE VRAM Power Fail",
		"1002": "RSX VRAM Power Fail",
		"1004": "AC/DC Power Fail",
		"1103": "Thermal Error",
		"1200": "BE Thermal Error",
		"1201": "RSX Thermal Error",
		"1203": "BE VR Thermal Error",
		"1204": "SB Thermal Error",
		"1205": "EE+GS Thermal Error",
		"1301": "BE PLL Unlick",
		"14FF": "Check Stop",
		"1601": "BE Livelock Detection",
		"1701": "BE Attention",
		"1802": "RSX INIT",
		"1900": "RTC Error (voltage drop)",
		"1901": "RTC Error (oscillation stop)",
		"1902": "RTC Error (Access Error)",
		"2":    "Fatal error",
		"2001": "BE Error (IC1001)",
		"2002": "RSX Error (IC2001)",
		"2003": "SB Error (IC3001)",
		"2010": "Clock Generator Error (IC5001)",
		"2011": "Clock Generator Error (IC5003)",
		"2012": "Clock Generator Error (IC5002)",
		"2013": "Clock Generator Error (IC5004)",
		"2020": "HDMI Error (IC2502)",
		"2022": "DVE Error (IC2406)",
		"2030": "Thermal Sensor Error (IC1101)",
		"2031": "Thermal Sensor Error (IC2101)",
		"2033": "Thermal Sensor Error (IC3101)",
		"2101": "BE Error (IC1001)",
		"2102": "RSX Error (IC2001)",
		"2103": "SB Error (IC3001",
		"2110": "Clock Generator Error (IC5001)",
		"2111": "Clock Generator Error (IC5003)",
		"2112": "Clock Generator Error (IC5002)",
		"2113": "Clock Generator Error (IC5004)",
		"2120": "HDMI Error (IC2502)",
		"2122": "DVE Error (IC2406)",
		"2130": "Thermal Sensor Error (IC1101)",
		"2131": "Thermal Sensor Error (IC2101)",
		"2133": "Thermal Sensor Error (IC3101)",
		"2203": "SB Error (IC3001)",
		"3":    "Fatal booting error",
		"3000": "POWER FAIL",
		"3001": "POWER FAIL",
		"3002": "POWER FAIL",
		"3003": "POWER FAIL",
		"3004": "POWER FAIL",
		"3010": "BE Error (IC1001)",
		"3011": "BE Error (IC1001)",
		"3012": "BE Error (IC1001)",
		"3020": "BE Error (IC1001)",
		"3030": "BE Error (IC1001)",
		"3031": "BE Error (IC1001)",
		"3032": "BE Error (IC1001)",
		"3033": "BE Error (IC1001)",
		"3034": "BE Error (IC1001)",
		"3035": "BE-RSX Error (IC1001-IC2001)",
		"3036": "BE-RSX Error (IC1001-IC2001)",
		"3037": "BE-RSX Error (IC1001-IC2001)",
		"3038": "BE-SB Error (IC1001-IC3001)",
		"3039": "BE-SB Error (IC1001-IC3001)",
		"3040": "Flash controller Error (IC3801)",
		"4":    "Data error",
		"4001": "BE Error (IC1001)",
		"4002": "RSX Error (IC2001)",
		"4003": "SB Error (IC3001)",
		"4011": "BE Error (IC1001)",
		"4101": "BE Error (IC1001)",
		"4102": "RSX Error (IC2001)",
		"4103": "SB Error (IC3001)",
		"4111": "BE Error (IC1001)",
		"4201": "BE Error (IC1001)",
		"4202": "RSX Error (IC2001)",
		"4203": "SB Error (IC3001)",
		"4211": "BE Error (IC1001)",
		"4212": "RSX Error (IC2001)",
		"4221": "BE Error (IC1001)",
		"4222": "RSX Error (IC2001)",
		"4231": "BE Error (IC1001)",
		"4261": "BE Error (IC1001)",
		"4301": "BE Error (IC1001)",
		"4302": "RSX Error (IC2001)",
		"4303": "SB Error (IC3001)",
		"4311": "BE Error (IC1001)",
		"4312": "RSX Error (IC2001)",
		"4321": "BE Error (IC1001)",
		"4322": "RSX Error (IC2001)",
		"4332": "RSX Error (IC2001)",
		"4341": "BE Error (IC1001)",
		"4401": "BE or RSX Error (IC1001 or IC2001)",
		"4402": "BE or RSX Error (IC1001 or IC2001)",
		"4403": "BE or SB Error (IC1001 or IC3001)",
		"4411": "BE or RSX Error (IC1001 or IC2001)",
		"4412": "BE or RSX Error (IC1001 or IC2001)",
		"4421": "BE or RSX Error (IC1001 or IC2001)",
		"4422": "BE or RSX Error (IC1001 or IC2001)",
		"4432": "BE or RSX Error (IC1001 or IC2001)",
		"4441": "BE or SB Error (IC1001 or IC3001)",
	}

	extCmd = map[string]cmdMeta{
		"BOOT":       {subs: "TEST,CONT"},
		"SHUTDOWN":   {},
		"HALT":       {},
		"BOOTENABLE": {},
		"AUTH1":      {},
		"AUTH2":      {},
		"AUTHVER":    {subs: "SET,GET"},
		"EEP":        {subs: "INIT,SET,GET"},
		"PDAREA":     {subs: "SET,GET"},
		"CSAREA":     {subs: "SET,GET"},
		"VID":        {subs: "GET"},
		"CID":        {subs: "GET"},
		"ECID":       {subs: "GET"},
		"REV":        {subs: "SB"},
		"SPU":        {subs: "INFO"},
		"KSV":        {},
		"FAN":        {subs: "SETPOLICY,GETPOLICY,START,STOP,SETDUTY,GETDUTY"},
		"R8":         {},
		"W8":         {},
		"R16":        {},
		"W16":        {},
		"R32":        {},
		"W32":        {},
		"RBE":        {},
		"WBE":        {},
		"PORTSTAT":   {},
		"VER":        {},
		"BUZ":        {},
		"SERVFAN":    {},
		"ERRLOG":     {subs: "START,STOP,GET,CLEAR"},
	}

	intCmd = map[string]cmdMeta{
		"becount":            {description: "Display bringup/shutdown count + Power-on time"},
		"bepgoff":            {description: "BE power grid off"},
		"bepkt":              {subs: "show,set,unset,mode,debug,help", description: "Packet permissions"},
		"bestat":             {description: "Get status of BE"},
		"boardconfig":        {description: "Displays board configuration"},
		"bootbeep":           {subs: "stat,on,off", description: "Boot beep"},
		"bringup":            {description: "Turn PS3 on"},
		"bsn":                {description: "Get board serial number"},
		"bstatus":            {description: "HDMI related status"},
		"buzz":               {description: "Activate buzzer", params: "freq"},
		"buzzpattern":        {description: "Buzzer pattern", params: "freq,pattern,count"},
		"clear_err":          {subs: "last,eeprom,all", description: "Clear errors"},
		"clearerrlog":        {description: "Clears error log"},
		"comm":               {description: "Communication mode"},
		"commt":              {subs: "help,start,stop,send", description: "Manual BE communication"},
		"cp":                 {subs: "ready,busy,reset,beepremote,beep2kn1n3,beep2kn2n3", description: "CP control commands"},
		"csum":               {description: "Firmware checksum"},
		"devpm":              {subs: "ata,pci,pciex,rsx", description: "Device power management"},
		"diag":               {description: "Diag (execute without param to show help)"},
		"disp_err":           {description: "Displays errors"},
		"duty":               {subs: "get,set,getmin,setmin,getmax,setmax,getinmin,setinmin,getinmax,setinmax", description: "Fan policy"},
		"dve":                {subs: "help,set,save,show", description: "DVE chip parameters"},
		"eepcsum":            {description: "Shows eeprom checksum"},
		"eepromcheck":        {description: "Check eeprom", params: "id"},
		"eeprominit":         {description: "Init eeprom", params: "id"},
		"ejectsw":            {description: "Eject switch"},
		"errlog":             {description: "Gets the error log"},
		"fancon":             {description: "Does nothing"},
		"fanconautotype":     {description: "Does nothing"},
		"fanconmode":         {subs: "get", description: "Fan control mode"},
		"fanconpolicy":       {subs: "get,set,getini,setini", description: "Fan control policy"},
		"fandiag":            {description: "Fan test"},
		"faninictrl":         {description: "Does nothing"},
		"fanpol":             {description: "Does nothing"},
		"fanservo":           {description: "Does nothing"},
		"fantbl":             {subs: "get,set,getini,setini,gettable,settable", description: "Fan table"},
		"firmud":             {description: "Firmware update"},
		"geterrlog":          {description: "Gets error log", params: "id"},
		"getrtc":             {description: "Gets rtc"},
		"halt":               {description: "Halts syscon"},
		"hdmi":               {description: "HDMI (various commands, use help)"},
		"hdmiid":             {description: "Get HDMI id's"},
		"hdmiid2":            {description: "Get HDMI id's"},
		"hversion":           {description: "Platform ID"},
		"hyst":               {subs: "get,set,getini,setini", description: "Temperature zones"},
		"lasterrlog":         {description: "Last error from log"},
		"ledmode":            {description: "Get led mode", params: "id,id"},
		"LS":                 {description: "LabStation Mode"},
		"ltstest":            {subs: "get,set", description: "?Temp related? values"},
		"osbo":               {description: "Sets 0x2000F60"},
		"patchcsum":          {description: "Patch checksum"},
		"patchvereep":        {description: "Patch version eeprom"},
		"patchverram":        {description: "Patch version ram"},
		"poll":               {description: "Poll log"},
		"portscan":           {description: "Scan port", params: "port"},
		"powbtnmode":         {description: "Power button mode", params: "mode"},
		"powerstate":         {description: "Get power state"},
		"powersw":            {description: "Power switch"},
		"powupcause":         {description: "Power up cause"},
		"printmode":          {description: "Set printmode", params: "mode"},
		"printpatch":         {description: "Prints patch"},
		"r":                  {description: "Read byte from SC", params: "offset,length"},
		"r16":                {description: "Read word from SC", params: "offset,length"},
		"r32":                {description: "Read dword from SC", params: "offset,length"},
		"r64":                {description: "Read qword from SC", params: "offset,length"},
		"r64d":               {description: "Read qword data from SC", params: "offset,length"},
		"rbe":                {description: "Read from BE", params: "offset"},
		"recv":               {description: "Receive something"},
		"resetsw":            {description: "Reset switch"},
		"restartlogerrtoeep": {description: "Reenable error logging to eeprom"},
		"revision":           {description: "Get softid"},
		"rrsxc":              {description: "Read from RSX", params: "offset,length"},
		"rtcreset":           {description: "Reset RTC"},
		"scagv2":             {description: "Auth related?"},
		"scasv2":             {description: "Auth related?"},
		"scclose":            {description: "Close syscon"},
		"scopen":             {description: "Open syscon"},
		"send":               {description: "Send something", params: "variable"},
		"shutdown":           {description: "PS3 shutdown"},
		"startlogerrtsk":     {description: "Start error log task"},
		"stoplogerrtoeep":    {description: "Stop error logging to eeprom"},
		"stoplogerrtsk":      {description: "Stop error log task"},
		"syspowdown":         {description: "System power down", params: "param,param,param"},
		"task":               {description: "Print tasks"},
		"thalttest":          {description: "Does nothing"},
		"thermfatalmode":     {subs: "canboot,cannotboot", description: "Set thermal boot mode"},
		"therrclr":           {description: "Thermal register clear"},
		"thrm":               {description: "Does nothing"},
		"tmp":                {description: "Get temperature", params: "zone"},
		"trace":              {description: "Trace tasks (use help)"},
		"trp":                {subs: "get,set,getini,setini", description: "Temperature zones"},
		"tsensor":            {description: "Get raw temperature", params: "sensor"},
		"tshutdown":          {subs: "get,set,getini,setini", description: "Thermal shutdown"},
		"tshutdowntime":      {description: "Thermal shutdown time", params: "time"},
		"tzone":              {description: "Show thermal zones"},
		"version":            {description: "SC firmware version"},
		"w":                  {description: "Write byte to SC", params: "offset,value"},
		"w16":                {description: "Write word to SC", params: "offset,value"},
		"w32":                {description: "Write bword to SC", params: "offset,value"},
		"w64":                {description: "Write qword to SC", params: "offset,value"},
		"wbe":                {description: "Write to BE", params: "offset,value"},
		"wmmto":              {subs: "get", description: "Get watchdog timeout"},
		"wrsxc":              {description: "Write to RSX", params: "offset,value"},
		"xdrdiag":            {subs: "start,info,result", description: "XDR diag"},
		"xiodiag":            {description: "XIO diag"},
		"xrcv":               {description: "Xmodem receive"},
	}
)
